SELECT MAX(salary) FROM teacher  -- SELECT HIGHEST SALARY
SELECT MIN(salary) FROM teacher  -- SELECT LOWEST SALARY
SELECT COUNT(*) FROM teacher  -- SELECT NUMBER OF ROWS
SELECT AVG(*) FROM teacher  -- SELECT NUMBER OF ROWS



SELECT * FROM students WHERE student_name LIKE 'A' -- SELECT ALL ROW WHERE STUDENT NAME CONTAINS 'A'
SELECT MAX(salary) FROM teacher WHERE salary NOT IN (SELECT MAX(salary) FROM teacher) -- SELECT SECOND HIGHEST SALARY


SELECT * FROM students WHERE salary BETWEEN 1000 AND 5000 